---
- name: New User Playbook
  hosts: all
  become: yes

  tasks:
    - name: create User John
      tags: always
      ansible.builtin.user:
        name: John
        home: /better-place/john
        uid: 1234
        
    - name: add sudoers file for John
      tags: always
      copy:
        src: sudoers_john
        dest: etc/sudoers.d/John
        name: John
        mode: 0440
          
    - name: Install a tmux and vim
      ansible.builtin.apt:
        pkg:
        - tmux
        - vim

