---
- name: New User Playbook
  hosts: localhost
  become: yes

  tasks:
    - name: create User John
      tags: always
      ansible.builtin.user:
        name: John
        home: /better-place/john
        uid: 1234
    - name: Copy nice-script.sh to the user's home directory
      copy:
        src: /nice-script.sh
        dest: /better-place/john/nice-script.sh
        mode: '0755'
        owner: john
        group: john
       
    - name: add sudoers file for John
      tags: always
      copy:
        src: sudoers_john
        dest: etc/sudoers.d/John
        name: John
        mode: 0440
          
    - name: Install a tmux and vim
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        with_items:
        - tmux
        - vim

    - name: Download Terraform binary
      get_url:
        url: "https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip"
        dest: "/tmp/terraform.zip"

    - name: Unzip Terraform binary
      unarchive:
        src: "/tmp/terraform.zip"
        dest: "/usr/local/bin"
        remote_src: yes
        creates: "/usr/local/bin/terraform"

    - name: Set permissions for Terraform
      file:
        path: "/usr/local/bin/terraform"
        mode: "0755"
