---
- name: New User Playbook
  hosts: all
  become: yes
  tasks:
    - name: Create skeleton directory for new users
      file:
        path: /etc/skel
        state: directory

    - name: Create nice-script.sh locally
      copy:
        content: |
          #!/bin/bash
          df -a -T -h
        dest: nice-script.sh
        mode: 0755

    - name: Copy nice-script.sh to skeleton directory
      copy:
        src: nice-script.sh
        dest: /etc/skel/nice-script.sh
        mode: 0755

    - name: create User John
      tags: always
      ansible.builtin.user:
        name: John
        home: /better-place/john
        uid: 1234

       

    - name: Allow user 'john' to run whoami with sudo
      lineinfile:
        path: /etc/sudoers
        line: 'john ALL=(ALL) NOPASSWD: /usr/bin/whoami'
        validate: 'visudo -cf %s'
          

    - name: Install packages
      apt:
        name:
          - tmux
          - vim
        state: present

    - name: Install Terraform CLI
      block:
        - name: Download Terraform archive
          get_url:
            url: "https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip"
            dest: /tmp/terraform.zip

        - name: Unzip Terraform archive
          unarchive:
            src: /tmp/terraform.zip
            dest: /usr/local/bin/
            remote_src: yes
            mode: '0755'
          notify: Update PATH environment variable

  handlers:
    - name: Update PATH environment variable
      shell: echo "export PATH=$PATH:/usr/local/bin" >> /etc/profile
      changed_when: false

